name = "IEEE9BusEPICS"
uuid = "d2e47893-2b50-4736-87fd-ec014471b102"
authors = ["rodrigomha <rodrigomha@gmail.com>"]
version = "0.1.0"

[deps]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PowerFlows = "94fada2c-fd9a-4e89-8d82-81405f5cb4f6"
PowerNetworkMatrices = "bed98974-b02a-5e2f-9fe0-a103f5c450dd"
PowerSimulations = "e690365d-45e2-57bb-ac84-44ba829e73c4"
PowerSimulationsDynamics = "398b2ede-47ed-4edc-b52e-69e4a48b4336"
PowerSystemCaseBuilder = "f00506e0-b84f-492a-93c2-c0a9afc4364e"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
StorageSystemsSimulations = "e2f1a126-19d0-4674-9252-42b2384f8e3c"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[compat]
HiGHS = "1.19.0"
OrdinaryDiffEq = "=6.103.0"
PowerFlows = "=0.9.0"
PowerNetworkMatrices = "=0.12.1"
PowerSimulations = "=0.30.2"
PowerSimulationsDynamics = "=0.15.0"
PowerSystemCaseBuilder = "=1.3.11"
PowerSystems = "=4.6.2"
StorageSystemsSimulations = "0.12.0"
Sundials = "4.28.0"
