name = "IEEE9BusEPICS"
uuid = "d2e47893-2b50-4736-87fd-ec014471b102"
authors = ["rodrigomha <rodrigomha@gmail.com>"]
version = "0.1.0"

[deps]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
PowerSimulations = "e690365d-45e2-57bb-ac84-44ba829e73c4"
PowerSystemCaseBuilder = "f00506e0-b84f-492a-93c2-c0a9afc4364e"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"

[compat]
HiGHS = "1.19.0"
PowerSimulations = "=0.30.2"
PowerSystemCaseBuilder = "=1.3.11"
PowerSystems = "=4.6.2"
